version: "3.9"

services:
  streamlit-app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    env_file:
      - .env     # Carga tus secrets desde .env
    restart: unless-stopped

 
